### ISSUE TITLE
Implement Initial Classifier Async Module

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/Classifier#11]
### Tasks
- [x] Initialization (logging, read initial definition)
- [x] Add Validity check submodule
- [x] Add RPC Registered Existence check submodule

**Comment by mfuroyama** [comment]
The existence module just passes 'valid' for now, until we implement the model
