### ISSUE TITLE
Implement HTTP-based RPC requests in the Handler service Emulation handler

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/Classifier#6]
Using the HTTP endpoint interface provided by the VICS Emulation Server, modify the emulation handler to replace the raw client socket implementation with an HTTP client implementation. The emulation handler should, at a minimum, pass the connection information (e.g. session ID, transaction ID) along with the RPC request per the HTTP endpoint specification. The handler should also process any errors returned by the endpoint.

### Notes
The RPC Router should maintains session ID and info, and should attach transaction IDs to each individual RPC reqeust. It would make sense to attach the session and transaction IDs to downstream requests to the VICS Emulation Server. This assumes that a new mechanism to send/receive RPC emulation requests/respones to the VICS Emulation Server has already been worked out.

### Tasks
* [ ] Replace the raw socket mechanism used by the RPC Router to communicate with the VICS Emulation Server with an appropriate HTTP mechanism (request, axios, etc.)
* [ ] Ensure that the requests, at a minimum, contain the following information in the request body:
    * `sessionId` (connection ID)
    * `transactionId`
* [ ] Handle any errors returned by the HTTP mechanism in the **RPC** objects
